# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FetcherGui.ui'
#
# Created: Mon Feb  9 14:21:50 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class ClickQLabel(QtGui.QLabel):
    """ label that emits a clicked() signal when a mousePressEvent occurs """ 
    def __init__(self, parent):
        QtGui.QLabel.__init__(self, parent)
        
    def mousePressEvent(self, mouseEvent):
        self.emit(QtCore.SIGNAL("clicked()"))

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(513, 573)
        Dialog.setMinimumSize(QtCore.QSize(513, 573))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.coverTab = QtGui.QWidget()
        self.coverTab.setObjectName("coverTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.coverTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchHorizontalLayout = QtGui.QHBoxLayout()
        self.searchHorizontalLayout.setObjectName("searchHorizontalLayout")
        self.searchLineEdit = QtGui.QLineEdit(self.coverTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchLineEdit.sizePolicy().hasHeightForWidth())
        self.searchLineEdit.setSizePolicy(sizePolicy)
        self.searchLineEdit.setMinimumSize(QtCore.QSize(318, 25))
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.searchHorizontalLayout.addWidget(self.searchLineEdit)
        self.pushButtonSearch = QtGui.QPushButton(self.coverTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSearch.sizePolicy().hasHeightForWidth())
        self.pushButtonSearch.setSizePolicy(sizePolicy)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.searchHorizontalLayout.addWidget(self.pushButtonSearch)
        self.verticalLayout_2.addLayout(self.searchHorizontalLayout)
        self.listWidget = QtGui.QListWidget(self.coverTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(100, 80))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.coverLabel = ClickQLabel(self.coverTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coverLabel.sizePolicy().hasHeightForWidth())
        self.coverLabel.setSizePolicy(sizePolicy)
        self.coverLabel.setMinimumSize(QtCore.QSize(0, 300))
        self.coverLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.coverLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.coverLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.coverLabel.setObjectName("coverLabel")
        self.verticalLayout_2.addWidget(self.coverLabel)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonNext = QtGui.QPushButton(self.coverTab)
        self.pushButtonNext.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonNext.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButtonNext.setAutoDefault(False)
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.gridLayout.addWidget(self.pushButtonNext, 2, 5, 1, 1)
        self.pushButtonPrev = QtGui.QPushButton(self.coverTab)
        self.pushButtonPrev.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonPrev.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButtonPrev.setAutoDefault(False)
        self.pushButtonPrev.setObjectName("pushButtonPrev")
        self.gridLayout.addWidget(self.pushButtonPrev, 2, 4, 1, 1)
        self.pushButtonSave = QtGui.QPushButton(self.coverTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSave.sizePolicy().hasHeightForWidth())
        self.pushButtonSave.setSizePolicy(sizePolicy)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(55, 29))
        self.pushButtonSave.setAutoDefault(False)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout.addWidget(self.pushButtonSave, 2, 0, 1, 1)
        self.pushButtonDelete = QtGui.QPushButton(self.coverTab)
        self.pushButtonDelete.setMinimumSize(QtCore.QSize(55, 0))
        self.pushButtonDelete.setAutoDefault(False)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.gridLayout.addWidget(self.pushButtonDelete, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.coverTab, "")
        self.configurationTab = QtGui.QWidget()
        self.configurationTab.setObjectName("configurationTab")
        self.gridLayout_4 = QtGui.QGridLayout(self.configurationTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtGui.QGroupBox(self.configurationTab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.discogsSpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.discogsSpinBox.setMinimum(0)
        self.discogsSpinBox.setMaximum(15)
        self.discogsSpinBox.setProperty("value", QtCore.QVariant(3))
        self.discogsSpinBox.setObjectName("discogsSpinBox")
        self.gridLayout_3.addWidget(self.discogsSpinBox, 1, 0, 1, 1)
        self.lastfmSpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.lastfmSpinBox.setMaximum(1)
        self.lastfmSpinBox.setProperty("value", QtCore.QVariant(1))
        self.lastfmSpinBox.setObjectName("lastfmSpinBox")
        self.gridLayout_3.addWidget(self.lastfmSpinBox, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 4, 1, 1)
        self.discogsLinkLabel = QtGui.QLabel(self.groupBox_2)
        self.discogsLinkLabel.setOpenExternalLinks(True)
        self.discogsLinkLabel.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.discogsLinkLabel.setObjectName("discogsLinkLabel")
        self.gridLayout_3.addWidget(self.discogsLinkLabel, 1, 3, 1, 1)
        self.discogsLabel = QtGui.QLabel(self.groupBox_2)
        self.discogsLabel.setPixmap(QtGui.QPixmap("../../../pytest2/src/discogs/discogs.gif"))
        self.discogsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.discogsLabel.setObjectName("discogsLabel")
        self.gridLayout_3.addWidget(self.discogsLabel, 1, 1, 1, 1)
        self.lastfmLinkLabel = QtGui.QLabel(self.groupBox_2)
        self.lastfmLinkLabel.setOpenExternalLinks(True)
        self.lastfmLinkLabel.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.lastfmLinkLabel.setObjectName("lastfmLinkLabel")
        self.gridLayout_3.addWidget(self.lastfmLinkLabel, 3, 3, 1, 1)
        self.lastfmLabel = QtGui.QLabel(self.groupBox_2)
        self.lastfmLabel.setPixmap(QtGui.QPixmap("../../../pytest2/src/discogs/lastfm.gif"))
        self.lastfmLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastfmLabel.setObjectName("lastfmLabel")
        self.gridLayout_3.addWidget(self.lastfmLabel, 3, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.configurationTab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.overWriteCheckBox = QtGui.QCheckBox(self.groupBox)
        self.overWriteCheckBox.setObjectName("overWriteCheckBox")
        self.verticalLayout_3.addWidget(self.overWriteCheckBox)
        self.idRadioButton = QtGui.QRadioButton(self.groupBox)
        self.idRadioButton.setChecked(True)
        self.idRadioButton.setObjectName("idRadioButton")
        self.verticalLayout_3.addWidget(self.idRadioButton)
        self.albumRadioButton = QtGui.QRadioButton(self.groupBox)
        self.albumRadioButton.setObjectName("albumRadioButton")
        self.verticalLayout_3.addWidget(self.albumRadioButton)
        self.fixedRadioButton = QtGui.QRadioButton(self.groupBox)
        self.fixedRadioButton.setObjectName("fixedRadioButton")
        self.verticalLayout_3.addWidget(self.fixedRadioButton)
        self.fixedLineEdit = QtGui.QLineEdit(self.groupBox)
        self.fixedLineEdit.setEnabled(False)
        self.fixedLineEdit.setObjectName("fixedLineEdit")
        self.verticalLayout_3.addWidget(self.fixedLineEdit)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 0, 2, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 257, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 4, 0, 1, 1)
        self.configButtonBox = QtGui.QDialogButtonBox(self.configurationTab)
        self.configButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.configButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.Save)
        self.configButtonBox.setCenterButtons(True)
        self.configButtonBox.setObjectName("configButtonBox")
        self.gridLayout_4.addWidget(self.configButtonBox, 3, 0, 1, 1)
        self.tabWidget.addTab(self.configurationTab, "")
        self.logTab = QtGui.QWidget()
        self.logTab.setObjectName("logTab")
        self.horizontalLayout = QtGui.QHBoxLayout(self.logTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logTextEdit = QtGui.QTextEdit(self.logTab)
        self.logTextEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.logTextEdit.setObjectName("logTextEdit")
        self.horizontalLayout.addWidget(self.logTextEdit)
        self.tabWidget.addTab(self.logTab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.fixedRadioButton, QtCore.SIGNAL("toggled(bool)"), self.fixedLineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.searchLineEdit)
        Dialog.setTabOrder(self.searchLineEdit, self.pushButtonSearch)
        Dialog.setTabOrder(self.pushButtonSearch, self.listWidget)
        Dialog.setTabOrder(self.listWidget, self.pushButtonSave)
        Dialog.setTabOrder(self.pushButtonSave, self.pushButtonDelete)
        Dialog.setTabOrder(self.pushButtonDelete, self.pushButtonPrev)
        Dialog.setTabOrder(self.pushButtonPrev, self.pushButtonNext)
        Dialog.setTabOrder(self.pushButtonNext, self.discogsSpinBox)
        Dialog.setTabOrder(self.discogsSpinBox, self.lastfmSpinBox)
        Dialog.setTabOrder(self.lastfmSpinBox, self.overWriteCheckBox)
        Dialog.setTabOrder(self.overWriteCheckBox, self.idRadioButton)
        Dialog.setTabOrder(self.idRadioButton, self.albumRadioButton)
        Dialog.setTabOrder(self.albumRadioButton, self.fixedRadioButton)
        Dialog.setTabOrder(self.fixedRadioButton, self.fixedLineEdit)
        Dialog.setTabOrder(self.fixedLineEdit, self.configButtonBox)
        Dialog.setTabOrder(self.configButtonBox, self.logTextEdit)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "DiscogsCoverFetcher", None, QtGui.QApplication.UnicodeUTF8))
        self.searchLineEdit.setToolTip(QtGui.QApplication.translate("Dialog", "Enter search term in the following form:\n"
"<artist> - <album>\n"
"and hit Return to perfom another search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSearch.setText(QtGui.QApplication.translate("Dialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setToolTip(QtGui.QApplication.translate("Dialog", "Choose to view your Local Covers or\n"
"covers from last.fm / discogs", None, QtGui.QApplication.UnicodeUTF8))
        self.coverLabel.setToolTip(QtGui.QApplication.translate("Dialog", "Click to fit cover to window size\n"
"[Alt+Z]", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonNext.setToolTip(QtGui.QApplication.translate("Dialog", "Show next cover\n"
"[Alt+Right]", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonNext.setText(QtGui.QApplication.translate("Dialog", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonNext.setShortcut(QtGui.QApplication.translate("Dialog", "Alt+Right", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPrev.setToolTip(QtGui.QApplication.translate("Dialog", "Show previous cover\n"
"[Alt+Left]", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPrev.setText(QtGui.QApplication.translate("Dialog", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPrev.setShortcut(QtGui.QApplication.translate("Dialog", "Alt+Left", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setToolTip(QtGui.QApplication.translate("Dialog", "Save to Local Covers", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("Dialog", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDelete.setToolTip(QtGui.QApplication.translate("Dialog", "Delete from Local Covers", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDelete.setText(QtGui.QApplication.translate("Dialog", "&Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.coverTab), QtGui.QApplication.translate("Dialog", "Cover&Fetcher", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Amount of Releases to Fetch", None, QtGui.QApplication.UnicodeUTF8))
        self.discogsSpinBox.setToolTip(QtGui.QApplication.translate("Dialog", "3 achieves good results, much more is not advised,\n"
"since the requests from discogs are limited per day and IP.", None, QtGui.QApplication.UnicodeUTF8))
        self.lastfmSpinBox.setToolTip(QtGui.QApplication.translate("Dialog", "last.fm either returns a release or not,\n"
"therefore only 0 or 1 cover are fetched.", None, QtGui.QApplication.UnicodeUTF8))
        self.discogsLinkLabel.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.discogs.com\"><span style=\" text-decoration: underline; color:#0057ae;\">discogs.com</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lastfmLinkLabel.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.last.fm\"><span style=\" text-decoration: underline; color:#0057ae;\">last.fm</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Filename Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.overWriteCheckBox.setToolTip(QtGui.QApplication.translate("Dialog", "Already existing covers can be overwritten.\n"
"Extensions are ignored, which means cover.jpg\n"
"will be \'overwritten\' (deleted) by cover.png\n"
"\n"
"Note, that for the Album Name scheme the names from\n"
"Discogs / Last.fm are used. These can be slightly different,\n"
"i.e. \'Pink and Green\' vs \'Pink And Green\'. In such a case\n"
"no file will not be overwritten, since \'Pink and Green.jpg\' and\n"
"\'Pink And Green.jpg\' are different filenames.", None, QtGui.QApplication.UnicodeUTF8))
        self.overWriteCheckBox.setText(QtGui.QApplication.translate("Dialog", "Allow overwriting of existing cover", None, QtGui.QApplication.UnicodeUTF8))
        self.idRadioButton.setToolTip(QtGui.QApplication.translate("Dialog", "Filenames (IDs) from Discogs and Last.FM are used,\n"
"which will result in names like R-170384-001.jpg", None, QtGui.QApplication.UnicodeUTF8))
        self.idRadioButton.setText(QtGui.QApplication.translate("Dialog", "Use unambiguous filename from Discogs and Last.fm", None, QtGui.QApplication.UnicodeUTF8))
        self.albumRadioButton.setToolTip(QtGui.QApplication.translate("Dialog", "Use the album name from Discogs / Last.fm", None, QtGui.QApplication.UnicodeUTF8))
        self.albumRadioButton.setText(QtGui.QApplication.translate("Dialog", "Use album name", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedRadioButton.setToolTip(QtGui.QApplication.translate("Dialog", "Covers always get the same name\n"
"\n"
"Note: Don\'t provide a file extension here,\n"
"just use \'cover\' if you want your files \n"
"to be named \'cover.jpg\', \'cover.png\',..", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedRadioButton.setText(QtGui.QApplication.translate("Dialog", "Use fixed name:", None, QtGui.QApplication.UnicodeUTF8))
        self.fixedLineEdit.setText(QtGui.QApplication.translate("Dialog", "cover", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configurationTab), QtGui.QApplication.translate("Dialog", "&Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logTab), QtGui.QApplication.translate("Dialog", "&Log", None, QtGui.QApplication.UnicodeUTF8))

